---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wismaindo/public_html/
    - /usr/bin/rsync -avP --exclude='.env' --exclude='.htaccess' --exclude='index.php' --exclude='.git/' --exclude='storage/' ./ $DEPLOYPATH
