---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wismaindo/public_html/
    - /bin/cp $DEPLOYPATH.env /home/wismaindo/.env.backup
    - /bin/cp $DEPLOYPATH.htaccess /home/wismaindo/.htaccess.backup
    - /bin/cp ${DEPLOYPATH}index.php /home/wismaindo/index.php.backup
    - /bin/cp -R * $DEPLOYPATH
    - /usr/bin/php ${DEPLOYPATH}extract.php
    - /bin/cp /home/wismaindo/.env.backup $DEPLOYPATH.env
    - /bin/cp /home/wismaindo/.htaccess.backup $DEPLOYPATH.htaccess
    - /bin/cp /home/wismaindo/index.php.backup ${DEPLOYPATH}index.php
    - /opt/cpanel/composer/bin/composer install --no-dev --working-dir=$DEPLOYPATH
